---
- name: Install NixOS from GitHub flake onto prepared /mnt target
  hosts: xen
  become: true
  gather_facts: false
  # vars_files:
  #   - secrets.yml
  vars:
    mount_root: "/mnt"
    flake_ref: "github:dadatoa/turbo-octo-robot"
    flake_host: "nixdomu"
    nixos_install_no_root_password: true
    user: "operateur"
    vg_name: "nvme_vg"
    subvolumes:
      - boot
      - nix
      - persist

  tasks:
    - name: Ensure /mnt exists
      ansible.builtin.file:
        path: "{{ mount_root }}"
        state: directory
        mode: "0755"

    - name: Ensure expected mount points exist
      ansible.builtin.file:
        path: "{{ mount_root }}/{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ subvolumes }}"

    - name: Mount btrfs subvolumes
      ansible.posix.mount:
        path: "{{ mount_root }}/{{ item }}"
        src: "/dev/{{ vg_name }}/{{ hostname }}"
        fstype: btrfs
        opts: "subvol={{ item }},compress=zstd,noatime"
        state: ephemeral
      loop: "{{ subvolumes }}"

    - name: Install NixOS from GitHub flake
      ansible.builtin.command:
        cmd: >-
          nixos-install
          --root {{ mount_root }}
          --flake {{ flake_ref }}#{{ flake_host }}
          {{ '--no-root-passwd' if nixos_install_no_root_password else '' }}
      environment:
        NIX_CONFIG: "experimental-features = nix-command flakes"

    - name: Unount btrfs subvolumes
      ansible.posix.mount:
        path: "{{ mount_root }}/{{ item }}"
        src: "/dev/{{ vg_name }}/{{ hostname }}"
        fstype: btrfs
        opts: "subvol={{ item }},compress=zstd,noatime"
        state: unmounted
      loop: "{{ subvolumes }}"
