---
- name: Post-install provisioning for operateur user
  hosts: nixos-vm
  become: true
  gather_facts: false

  vars_files:
    - secrets.yml
  vars:
    target_user: "operateur"

  tasks:
    - name: Ensure operateur home .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        mode: "0700"

    - name: Authorize SSH keys for operateur
      ansible.posix.authorized_key:
        user: "{{ target_user }}"
        state: present
        key: "{{ item }}"
      loop: "{{ ssh_public_keys }}"

    - name: Bring Tailscale up with auth key
      ansible.builtin.command:
        cmd: "tailscale up --authkey {{ tskey }}?ephemeral=false&preauthorized=true' --advertise-tags=tag:testlab,tag=home"
      no_log: true
      become: true
